server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    gateway:
      routes:
        # Zone Management Service Route
        - id: zone-service
          uri: lb://zone-management-service
          predicates:
            - Path=/api/zones/**

        # Sensor Telemetry Service Route
        - id: sensor-service
          uri: lb://sensor-telemetry-service
          predicates:
            - Path=/api/sensors/**

        # Automation & Control Service Route
        - id: automation-service
          uri: lb://automation-control-service
          predicates:
            - Path=/api/automation/**

        # Crop Inventory Service Route
        - id: crop-service
          uri: lb://crop-inventory-service
          predicates:
            - Path=/api/crops/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437" # Base64 encoded secret key for HS256 algorithm
